### ISSUE TITLE
棒棒哒~

### ISSUE THREAD

**Issue by HanFuyan** [jk77me/Blog#1]
我也很喜欢锤子的风格~加油哈~

**Comment by LeslieJia** [comment]
╮(╯▽╰)╭ 刚刚完善了播放和在线搜索. 支持本地播放 Slider调节音量. 加入了友盟分享 搜索模块返回数据长度取消了限制谢谢你的支持哦                             原始邮件                             发件人: 灬小韩<notifications@github.com>收件人: LeslieJia/TMusic<TMusic@noreply.github.com>发送时间: 2015年9月9日(周三) 20:09主题: [TMusic] 棒棒哒~ (#1)我也很喜欢锤子的风格~加油哈~
